### PR TITLE
Source code uploaded

### PR DESCRIPTION
**Pull request by xlxr**

### CODE REVIEW

**Comment by rb004f** [comment]
@xlxr Please include a makefile or instructions on how to compile the code.

**Comment by xlxr** [comment]
@rb004f An instruction is added in the README.md file under src folder

**Comment by rb004f** [comment]
Thanks @xlxr, I need a little more detail on how to compile the code, esp when there are dependencies on third party libraries (I see at least one for your code). A typical way this is done is to include a makefile.  From what I can tell, you used visual studio to compile your code.  If so, including the visual studio project file(s) would be sufficient.

**Comment by xlxr** [comment]
Hi @rb004f, the "gurobi.c++" file I included in the code is used to run Gurobi solver, which needs to be download and installed from their website. I added a sentence to explain it in README.md file. Does it work?

**Pull request merged**
